# Initial Data Exploration
-------------------------------------

Messing around with a day's worth of PBS Accouting Data to see if we can figure anything useful out.

In [22]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [8]:
path = '../csv_output/summary.csv'
df = pd.read_csv(path)

df.head()

,id,date,r_type,resource,value,key
0,8,20180212,Q,queue,economy,NaN
1,9,20180212,Q,queue,economy,NaN
2,10,20180212,Q,queue,economy,NaN
3,11,20180212,Q,queue,economy,NaN
4,12,20180212,Q,queue,economy,NaN
5,13,20180212,Q,queue,economy,NaN
6,14,20180212,Q,queue,economy,NaN
7,15,20180212,S,NaN,NaN,NaN
8,15,20180212,S,queue,economy,NaN
9,15,20180212,S,account,"""SSSG0001""",NaN
10,15,20180212,S,Resource_List.place,scatter:exclhost,NaN
11,15,20180212,S,group,ncar,NaN
12,15,20180212,S,ctime,1518447436,NaN
13,15,20180212,S,resource_assigned.ncpus,4608,NaN
14,15,20180212,S,Resource_List.ncpus,2304,NaN
15,15,20180212,S,qtime,1518447436,NaN
16,15,20180212,S,Resource_List.mpiprocs,128,NaN
17,15,20180212,S,exec_vnode,(r1i0n0:ncpus=36)+(r1i0n1:ncpus=36)+(r1i0n2:nc...,NaN
18,15,20180212,S,Resource_List.select,64,mpiprocs:2
19,15,20180212,S,Resource_List.select,64,ncpus:36
20,15,20180212,S,Resource_List.select,64,ompthreads:18
21,15,20180212,S,Resource_List.select,32,ncpus:14
22,15,20180212,S,jobname,zhpt64.2,NaN
23,15,20180212,S,project,_pbs_project_default,NaN
24,15,20180212,S,start,1518447437,NaN
25,15,20180212,S,Resource_List.walltime,01:00:00,NaN
26,15,20180212,S,user,engel,NaN
27,15,20180212,S,Resource_List.nodect,64,NaN
28,15,20180212,S,etime,1518447436,NaN
29,15,20180212,S,exec_host,r1i0n0/0*36+r1i0n1/0*36+r1i0n2/0*36+r1i0n3/0*3...,NaN
...,...,...,...,...,...,...
70,18,20180212,S,Resource_List.mpiprocs,96,NaN
71,18,20180212,S,exec_vnode,(r1i0n0:ncpus=36)+(r1i0n1:ncpus=36)+(r1i0n2:nc...,NaN
72,18,20180212,S,Resource_List.select,48,mpiprocs:2
73,18,20180212,S,Resource_List.select,48,ncpus:36
74,18,20180212,S,Resource_List.select,48,ompthreads:18
75,18,20180212,S,jobname,zhpt48.2,NaN
76,18,20180212,S,project,_pbs_project_default,NaN
77,18,20180212,S,start,1518449574,NaN
78,18,20180212,S,Resource_List.walltime,01:00:00,NaN
79,18,20180212,S,user,engel,NaN
80,18,20180212,S,Resource_List.nodect,48,NaN
81,18,20180212,S,etime,1518449520,NaN
82,18,20180212,S,exec_host,r1i0n0/0*36+r1i0n1/0*36+r1i0n2/0*36+r1i0n3/0*3...,NaN
83,18,20180212,S,resource_assigned.mem,3148374144kb,NaN
84,20,20180212,E,qtime,1518447436,NaN
85,20,20180212,E,session,19902,NaN
86,20,20180212,E,project,_pbs_project_default,NaN
87,20,20180212,E,group,ncar,NaN
88,20,20180212,E,Exit_status,0,NaN
89,20,20180212,E,etime,1518449520,NaN
90,20,20180212,E,resources_used.cput,977:54:54,NaN
91,20,20180212,E,start,1518449574,NaN
92,20,20180212,E,resources_used.cpupercent,173218,NaN
93,20,20180212,E,exec_vnode,(r1i0n0:ncpus=36)+(r1i0n1:ncpus=36)+(r1i0n2:nc...,NaN
94,20,20180212,E,run_count,1,NaN
95,20,20180212,E,Resource_List.ncpus,1728,NaN
96,20,20180212,E,resources_used.mem,647553680kb,NaN
97,20,20180212,E,Resource_List.place,scatter:exclhost,NaN
98,20,20180212,E,Resource_List.mpiprocs,96,NaN
99,20,20180212,E,Resource_List.walltime,01:00:00,NaN

In [28]:
df = df.dropna(axis=0, subset=['resource'])

dfTime = df[df['resource'].str.contains('time')]
dfTime.head()

    id      date r_type                resource       value  key
12  15  20180212      S                   ctime  1518447436  NaN
15  15  20180212      S                   qtime  1518447436  NaN
25  15  20180212      S  Resource_List.walltime    01:00:00  NaN
28  15  20180212      S                   etime  1518447436  NaN
31  17  20180212      E                   qtime  1518447436  NaN

In [27]:
array = df.values
features = df.iloc[:, np.arange(1, len(df.columns), 1)]
labels = df.iloc[:, [0]]
feature_name = df.columns[1:len(df.columns)]

print(feature_name)

# feature extraction
# model = LogisticRegression()
# rfe = RFE(model, 3)
# fit = rfe.fit(features, labels)

# print("Num Features: %d") % fit.n_features_
# print("Selected Features: %s") % fit.support_
# print("Feature Ranking: %s") % fit.ranking_

Index([u'date', u'r_type', u'resource', u'value', u'key'], dtype='object')